name: Build ZMK firmware
on: 
  workflow_dispatch:
  # push:
  #   paths:
  #     - config/**
  #     - boards/**
  #     - build.yaml
 
jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@930b5cc058698986fabc1be96427c14937e983ea
 